# Generated by Django 6.0.2 on 2026-03-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('dep_name', models.CharField(max_length=100)),
            ],
        ),
    ]
