# Generated by Django 6.0.2 on 2026-03-03 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.task')),
            ],
        ),
    ]
