# Generated by Django 6.0.2 on 2026-03-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('updated_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.task')),
            ],
        ),
    ]
